/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import CONTROLADORES.ClienteControlador;
import CONTROLADORES.TipoPagoControlador;
import MODELOS.ClienteBo;
import MODELOS.TipoPagoBo;
import MODELOS.TipoPagoVo;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class VistaPago extends javax.swing.JFrame {

    /**
     * Creates new form VistaPago
     */
    public VistaPago() {
        initComponents();
        jPpagodia.setVisible(true);
        jPcongelarpago.setVisible(false);
        jPvencido.setVisible(false);
        jLvalrut1.setText("Valor: $");
        TipoPagoBo modelotp = new TipoPagoBo();
        tpago = new TipoPagoControlador(this,modelotp);
        ClienteBo modelo;
        try {
            modelo = new ClienteBo();
            ClienteControlador cliente  = new ClienteControlador(this,modelo);
        } catch (Exception ex) {
            Logger.getLogger(VistaPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private TipoPagoControlador tpago;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBpagocongelar = new javax.swing.JButton();
        jBpagodia = new javax.swing.JButton();
        jBpagovencido = new javax.swing.JButton();
        jPpagodia = new javax.swing.JPanel();
        jDfechainicial = new com.toedter.calendar.JDateChooser("yyyy/MM/dd", "####/##/##", '_');
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTbusval = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTableclientes = new javax.swing.JTable();
        jBaggpago = new javax.swing.JButton();
        jLvalrut1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLvalrut = new javax.swing.JLabel();
        jDfechafinal = new com.toedter.calendar.JDateChooser("yyyy/MM/dd", "####/##/##", '_');
        jLtitulof = new javax.swing.JLabel();
        jCtpago = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLnumMeses = new javax.swing.JLabel();
        jCmeses = new javax.swing.JComboBox<>();
        jLvalT = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLvalorTotal = new javax.swing.JLabel();
        jPcongelarpago = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTTablepago = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPvencido = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTTablepagosvencidos = new javax.swing.JTable();
        jBmarcarVisto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 42, 42));

        jButton4.setBackground(new java.awt.Color(42, 42, 42));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/volver.png"))); // NOI18N
        jButton4.setToolTipText("Volver");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/001-pago.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rutina-Pagos");

        jBpagocongelar.setBackground(new java.awt.Color(42, 42, 42));
        jBpagocongelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBpagocongelar.setForeground(new java.awt.Color(255, 255, 255));
        jBpagocongelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/010-reloj-de-arena.png"))); // NOI18N
        jBpagocongelar.setText("Consultar");
        jBpagocongelar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBpagocongelar.setBorderPainted(false);
        jBpagocongelar.setFocusPainted(false);
        jBpagocongelar.setFocusable(false);
        jBpagocongelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBpagocongelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpagocongelarActionPerformed(evt);
            }
        });

        jBpagodia.setBackground(new java.awt.Color(255, 255, 255));
        jBpagodia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBpagodia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/009-efectivo.png"))); // NOI18N
        jBpagodia.setText("Pagos");
        jBpagodia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBpagodia.setBorderPainted(false);
        jBpagodia.setFocusPainted(false);
        jBpagodia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBpagodia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpagodiaActionPerformed(evt);
            }
        });

        jBpagovencido.setBackground(new java.awt.Color(42, 42, 42));
        jBpagovencido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBpagovencido.setForeground(new java.awt.Color(255, 255, 255));
        jBpagovencido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/019-calendario-2.png"))); // NOI18N
        jBpagovencido.setText("Vencidos");
        jBpagovencido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBpagovencido.setBorderPainted(false);
        jBpagovencido.setFocusPainted(false);
        jBpagovencido.setFocusable(false);
        jBpagovencido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBpagovencido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpagovencidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBpagocongelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBpagodia, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addComponent(jBpagovencido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jBpagodia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBpagocongelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBpagovencido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 450));

        jPpagodia.setBackground(new java.awt.Color(255, 255, 255));
        jPpagodia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPpagodia.add(jDfechainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 200, 31));

        jLabel12.setText("Seleccionar fecha");
        jPpagodia.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel5.setText("Ingrese palabra o número:");
        jPpagodia.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));
        jPpagodia.add(jTbusval, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 210, 178, 25));

        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/004-busqueda.png"))); // NOI18N
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });
        jPpagodia.add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jTTableclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTTableclientes);

        jPpagodia.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 246, 552, 150));

        jBaggpago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/009-efectivo.png"))); // NOI18N
        jBaggpago.setText("Pagar");
        jBaggpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaggpagoActionPerformed(evt);
            }
        });
        jPpagodia.add(jBaggpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLvalrut1.setText("Valor:");
        jPpagodia.add(jLvalrut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jButton1.setText("Cambiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPpagodia.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));
        jPpagodia.add(jLvalrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 56, -1, 14));
        jPpagodia.add(jDfechafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 200, 31));

        jLtitulof.setText("Fecha final");
        jPpagodia.add(jLtitulof, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jCtpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtpagoActionPerformed(evt);
            }
        });
        jPpagodia.add(jCtpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 229, 31));

        jLabel3.setText("Seleccionar tipo de pago");
        jPpagodia.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLnumMeses.setText("Número de meses:");
        jPpagodia.add(jLnumMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jPpagodia.add(jCmeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 60, -1));

        jLvalT.setText("Valor total:");
        jPpagodia.add(jLvalT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));
        jPpagodia.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 530, -1));

        jLvalorTotal.setText("$15000");
        jPpagodia.add(jLvalorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        getContentPane().add(jPpagodia, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 0, 590, 450));

        jPcongelarpago.setBackground(new java.awt.Color(255, 255, 255));

        jTTablepago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTTablepago);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/018-calendario-1.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setText("Mensualidades a la fecha");

        javax.swing.GroupLayout jPcongelarpagoLayout = new javax.swing.GroupLayout(jPcongelarpago);
        jPcongelarpago.setLayout(jPcongelarpagoLayout);
        jPcongelarpagoLayout.setHorizontalGroup(
            jPcongelarpagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcongelarpagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPcongelarpagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcongelarpagoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcongelarpagoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(162, 162, 162))))
            .addGroup(jPcongelarpagoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPcongelarpagoLayout.setVerticalGroup(
            jPcongelarpagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcongelarpagoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        getContentPane().add(jPcongelarpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 0, 590, 450));

        jPvencido.setBackground(new java.awt.Color(255, 255, 255));
        jPvencido.setPreferredSize(new java.awt.Dimension(400, 400));

        jTTablepagosvencidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTTablepagosvencidos);

        jBmarcarVisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/008-cuaderno.png"))); // NOI18N
        jBmarcarVisto.setText("Marcar como avisado");
        jBmarcarVisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmarcarVistoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel7.setText("Mensualidad vencida");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/019-calendario-2.png"))); // NOI18N

        javax.swing.GroupLayout jPvencidoLayout = new javax.swing.GroupLayout(jPvencido);
        jPvencido.setLayout(jPvencidoLayout);
        jPvencidoLayout.setHorizontalGroup(
            jPvencidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPvencidoLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvencidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPvencidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvencidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPvencidoLayout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(jLabel7)
                            .addGap(189, 189, 189)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvencidoLayout.createSequentialGroup()
                        .addComponent(jBmarcarVisto)
                        .addGap(206, 206, 206))))
        );
        jPvencidoLayout.setVerticalGroup(
            jPvencidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPvencidoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBmarcarVisto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPvencido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 590, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        VistaInicio vista = new VistaInicio();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBpagocongelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpagocongelarActionPerformed

        jPcongelarpago.setVisible(true);
        jPpagodia.setVisible(false);
        jPvencido.setVisible(false);
        if(!jBpagocongelar.isSelected()){
            jBpagocongelar.setBackground(new Color(255, 255, 255));
            jBpagocongelar.setForeground(new Color(42, 42, 42));
            jBpagodia.setBackground(new Color(42, 42, 42));
            jBpagodia.setForeground(new Color(255, 255, 255));
            jBpagovencido.setBackground(new Color(42, 42, 42));
            jBpagovencido.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_jBpagocongelarActionPerformed

    private void jBpagodiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpagodiaActionPerformed

        jPpagodia.setVisible(true);
        jPcongelarpago.setVisible(false);
        jPvencido.setVisible(false);
        if(!jBpagodia.isSelected()){
            jBpagocongelar.setBackground(new Color(42, 42, 42));
            jBpagocongelar.setForeground(new java.awt.Color(255, 255, 255));
            jBpagodia.setBackground(new Color(255, 255, 255));
            jBpagodia.setForeground(new Color(42, 42, 42));
            jBpagovencido.setBackground(new Color(42, 42, 42));
            jBpagovencido.setForeground(new Color(255, 255, 255));

        }
    }//GEN-LAST:event_jBpagodiaActionPerformed

    private void jBaggpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaggpagoActionPerformed
        
        
    }//GEN-LAST:event_jBaggpagoActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        
        
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dato = JOptionPane.showInputDialog(this, "Introduce un dato", "Valor rutina", JOptionPane.INFORMATION_MESSAGE);
        
        try{
            if(dato != null){
                if(dato.length() > 6){
            
                    JOptionPane.showMessageDialog(this, "El número debe tener máximo 6 dígitos","¡Error!",JOptionPane.ERROR_MESSAGE);
                
                }else{
                    TipoPagoVo pago = (TipoPagoVo)jCtpago.getSelectedItem();
                    pago.setValor(Integer.parseInt(dato));
                    tpago.setValor(pago);
                    jLvalrut1.setText("Valor: $"+dato);
                }
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe introducir solo caracteres numéricos","¡Error!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCtpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtpagoActionPerformed
        TipoPagoVo pago = (TipoPagoVo)jCtpago.getSelectedItem();
        int valor = pago.getValor();
        jLvalrut1.setText("Valor: $"+String.valueOf(valor));
        
        if(pago.getId() == 1){
            jDfechafinal.setVisible(false);
            jLtitulof.setVisible(false);
            jLnumMeses.setVisible(false);
            jCmeses.setVisible(false);
        }else{
            jDfechafinal.setVisible(true);
            jLtitulof.setVisible(true);
            jLnumMeses.setVisible(true);
            jCmeses.setVisible(true);
        }
        
    }//GEN-LAST:event_jCtpagoActionPerformed

    private void jBpagovencidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpagovencidoActionPerformed
        jPcongelarpago.setVisible(false);
        jPpagodia.setVisible(false);
        jPvencido.setVisible(true);
        if(!jBpagocongelar.isSelected()){
            jBpagocongelar.setBackground(new Color(42, 42, 42));
            jBpagocongelar.setForeground(new Color(255, 255, 255));
            jBpagodia.setBackground(new Color(42, 42, 42));
            jBpagodia.setForeground(new Color(255, 255, 255));
            jBpagovencido.setBackground(new Color(255, 255, 255));
            jBpagovencido.setForeground(new Color(42, 42, 42));

        }
    }//GEN-LAST:event_jBpagovencidoActionPerformed

    private void jBmarcarVistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmarcarVistoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBmarcarVistoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBaggpago;
    public javax.swing.JButton jBbuscar;
    public javax.swing.JButton jBmarcarVisto;
    public javax.swing.JButton jBpagocongelar;
    private javax.swing.JButton jBpagodia;
    public javax.swing.JButton jBpagovencido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    public javax.swing.JComboBox<String> jCmeses;
    public javax.swing.JComboBox<TipoPagoVo> jCtpago;
    public com.toedter.calendar.JDateChooser jDfechafinal;
    public com.toedter.calendar.JDateChooser jDfechainicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLnumMeses;
    private javax.swing.JLabel jLtitulof;
    private javax.swing.JLabel jLvalT;
    public javax.swing.JLabel jLvalorTotal;
    public javax.swing.JLabel jLvalrut;
    private javax.swing.JLabel jLvalrut1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPcongelarpago;
    private javax.swing.JPanel jPpagodia;
    public javax.swing.JPanel jPvencido;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTTableclientes;
    public javax.swing.JTable jTTablepago;
    public javax.swing.JTable jTTablepagosvencidos;
    public javax.swing.JTextField jTbusval;
    // End of variables declaration//GEN-END:variables
}
