/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import java.awt.Color;

/**
 *
 * @author mario
 */
public class VistaReportes extends javax.swing.JFrame {

    /**
     * Creates new form VistaReportes
     */
    public VistaReportes() {
        initComponents();
        jPrdiario.setVisible(true);//Inicializa el panel de reporte diario para que sea visible
        jPrmensual.setVisible(false);//Para que el panel mensual no sea visible
        jPranual.setVisible(false);//Para que el panel anual no sea visible
        jBgenerarpdf.setEnabled(false);//Para que el boton generar pdf no esté habilitado
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBrdiario = new javax.swing.JButton();
        jBrmensual = new javax.swing.JButton();
        jBranual = new javax.swing.JButton();
        jPrdiario = new javax.swing.JPanel();
        jDfecha = new com.toedter.calendar.JDateChooser("yyyy/MM/dd", "####/##/##", '_');
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTablereportes = new javax.swing.JTable();
        jBgenerarpdf = new javax.swing.JButton();
        jBgenerarrep = new javax.swing.JButton();
        jLvalTotal = new javax.swing.JLabel();
        jPrmensual = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jBgenerarrepmes = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTTablereportesmes = new javax.swing.JTable();
        jLasisTotalMes = new javax.swing.JLabel();
        jBgenerarpdfMes = new javax.swing.JButton();
        jMmes = new com.toedter.calendar.JMonthChooser();
        jYManio = new com.toedter.calendar.JYearChooser();
        jLabel15 = new javax.swing.JLabel();
        jLvalTotalMes = new javax.swing.JLabel();
        jPranual = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jBgenerarrepanio = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTTablereportesanio = new javax.swing.JTable();
        jLvalTotalAnio = new javax.swing.JLabel();
        jBgenerarpdfAnio = new javax.swing.JButton();
        jYanio = new com.toedter.calendar.JYearChooser();
        jLasisTotalAnio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 42, 42));

        jButton4.setBackground(new java.awt.Color(42, 42, 42));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/volver.png"))); // NOI18N
        jButton4.setToolTipText("Volver");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/003-analitica.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes");

        jBrdiario.setBackground(new java.awt.Color(255, 255, 255));
        jBrdiario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBrdiario.setForeground(new java.awt.Color(42, 42, 42));
        jBrdiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/014-calendario.png"))); // NOI18N
        jBrdiario.setText("Diario");
        jBrdiario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBrdiario.setBorderPainted(false);
        jBrdiario.setFocusPainted(false);
        jBrdiario.setFocusable(false);
        jBrdiario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBrdiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrdiarioActionPerformed(evt);
            }
        });

        jBrmensual.setBackground(new java.awt.Color(42, 42, 42));
        jBrmensual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBrmensual.setForeground(new java.awt.Color(255, 255, 255));
        jBrmensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/019-calendario-2.png"))); // NOI18N
        jBrmensual.setText("Mensual");
        jBrmensual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBrmensual.setBorderPainted(false);
        jBrmensual.setFocusPainted(false);
        jBrmensual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBrmensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrmensualActionPerformed(evt);
            }
        });

        jBranual.setBackground(new java.awt.Color(42, 42, 42));
        jBranual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBranual.setForeground(new java.awt.Color(255, 255, 255));
        jBranual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/018-calendario-1.png"))); // NOI18N
        jBranual.setText("Anual");
        jBranual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBranual.setBorderPainted(false);
        jBranual.setFocusPainted(false);
        jBranual.setFocusable(false);
        jBranual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBranual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBranualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBrdiario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBrmensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBranual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jBrdiario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBrmensual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBranual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 450));

        jPrdiario.setBackground(new java.awt.Color(255, 255, 255));
        jPrdiario.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel12.setText("Seleccionar fecha");

        jTTablereportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTTablereportes);

        jBgenerarpdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/009-pdf.png"))); // NOI18N
        jBgenerarpdf.setText("Generar pdf");

        jBgenerarrep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/008-archivo.png"))); // NOI18N
        jBgenerarrep.setText("Generar reporte");
        jBgenerarrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgenerarrepActionPerformed(evt);
            }
        });

        jLvalTotal.setText("Valor total:");

        javax.swing.GroupLayout jPrdiarioLayout = new javax.swing.GroupLayout(jPrdiario);
        jPrdiario.setLayout(jPrdiarioLayout);
        jPrdiarioLayout.setHorizontalGroup(
            jPrdiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrdiarioLayout.createSequentialGroup()
                .addGroup(jPrdiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPrdiarioLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jPrdiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jDfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPrdiarioLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jBgenerarrep)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPrdiarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPrdiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPrdiarioLayout.createSequentialGroup()
                        .addGroup(jPrdiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLvalTotal)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPrdiarioLayout.createSequentialGroup()
                        .addComponent(jBgenerarpdf)
                        .addGap(226, 226, 226))))
        );
        jPrdiarioLayout.setVerticalGroup(
            jPrdiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrdiarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(jDfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jBgenerarrep)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLvalTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBgenerarpdf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPrdiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 590, 450));

        jPrmensual.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Seleccionar año");

        jBgenerarrepmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/008-archivo.png"))); // NOI18N
        jBgenerarrepmes.setText("Generar reporte");
        jBgenerarrepmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgenerarrepmesActionPerformed(evt);
            }
        });

        jTTablereportesmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTTablereportesmes);

        jLasisTotalMes.setText("Asistencia total: ");

        jBgenerarpdfMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/009-pdf.png"))); // NOI18N
        jBgenerarpdfMes.setText("Generar pdf");

        jYManio.setToolTipText("");

        jLabel15.setText("Seleccionar mes");

        jLvalTotalMes.setText("Valor total:");

        javax.swing.GroupLayout jPrmensualLayout = new javax.swing.GroupLayout(jPrmensual);
        jPrmensual.setLayout(jPrmensualLayout);
        jPrmensualLayout.setHorizontalGroup(
            jPrmensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrmensualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPrmensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPrmensualLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel15)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel13))
                    .addGroup(jPrmensualLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jMmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jYManio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPrmensualLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jBgenerarrepmes))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPrmensualLayout.createSequentialGroup()
                        .addComponent(jLvalTotalMes)
                        .addGap(86, 86, 86)
                        .addComponent(jLasisTotalMes))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPrmensualLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBgenerarpdfMes)
                        .addGap(198, 198, 198)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPrmensualLayout.setVerticalGroup(
            jPrmensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrmensualLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPrmensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13))
                .addGap(16, 16, 16)
                .addGroup(jPrmensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMmes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYManio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jBgenerarrepmes)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPrmensualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvalTotalMes)
                    .addComponent(jLasisTotalMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBgenerarpdfMes)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPrmensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 590, 450));

        jPranual.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setText("Seleccionar año");

        jBgenerarrepanio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/008-archivo.png"))); // NOI18N
        jBgenerarrepanio.setText("Generar reporte");
        jBgenerarrepanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgenerarrepanioActionPerformed(evt);
            }
        });

        jTTablereportesanio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jTTablereportesanio.setFocusable(false);
        jScrollPane4.setViewportView(jTTablereportesanio);

        jLvalTotalAnio.setText("Valor total:");

        jBgenerarpdfAnio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/009-pdf.png"))); // NOI18N
        jBgenerarpdfAnio.setText("Generar pdf");
        jBgenerarpdfAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgenerarpdfAnioActionPerformed(evt);
            }
        });

        jYanio.setToolTipText("");

        jLasisTotalAnio.setText("Asistencia total: ");

        javax.swing.GroupLayout jPranualLayout = new javax.swing.GroupLayout(jPranual);
        jPranual.setLayout(jPranualLayout);
        jPranualLayout.setHorizontalGroup(
            jPranualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPranualLayout.createSequentialGroup()
                .addGroup(jPranualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPranualLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jBgenerarrepanio))
                    .addGroup(jPranualLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(jPranualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jYanio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPranualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPranualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPranualLayout.createSequentialGroup()
                                .addComponent(jLvalTotalAnio)
                                .addGap(85, 85, 85)
                                .addComponent(jLasisTotalAnio))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPranualLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBgenerarpdfAnio)
                .addGap(224, 224, 224))
        );
        jPranualLayout.setVerticalGroup(
            jPranualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPranualLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jYanio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jBgenerarrepanio)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPranualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvalTotalAnio)
                    .addComponent(jLasisTotalAnio))
                .addGap(4, 4, 4)
                .addComponent(jBgenerarpdfAnio)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPranual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 590, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        VistaInicio vista = new VistaInicio();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBrdiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrdiarioActionPerformed

        
    }//GEN-LAST:event_jBrdiarioActionPerformed

    private void jBrmensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrmensualActionPerformed

    }//GEN-LAST:event_jBrmensualActionPerformed

    private void jBranualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBranualActionPerformed
        
    }//GEN-LAST:event_jBranualActionPerformed

    private void jBgenerarrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgenerarrepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBgenerarrepActionPerformed

    private void jBgenerarrepmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgenerarrepmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBgenerarrepmesActionPerformed

    private void jBgenerarrepanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgenerarrepanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBgenerarrepanioActionPerformed

    private void jBgenerarpdfAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgenerarpdfAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBgenerarpdfAnioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBgenerarpdf;
    public javax.swing.JButton jBgenerarpdfAnio;
    public javax.swing.JButton jBgenerarpdfMes;
    public javax.swing.JButton jBgenerarrep;
    public javax.swing.JButton jBgenerarrepanio;
    public javax.swing.JButton jBgenerarrepmes;
    public javax.swing.JButton jBranual;
    public javax.swing.JButton jBrdiario;
    public javax.swing.JButton jBrmensual;
    private javax.swing.JButton jButton4;
    public com.toedter.calendar.JDateChooser jDfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLasisTotalAnio;
    public javax.swing.JLabel jLasisTotalMes;
    public javax.swing.JLabel jLvalTotal;
    public javax.swing.JLabel jLvalTotalAnio;
    public javax.swing.JLabel jLvalTotalMes;
    public com.toedter.calendar.JMonthChooser jMmes;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPranual;
    public javax.swing.JPanel jPrdiario;
    public javax.swing.JPanel jPrmensual;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTTablereportes;
    public javax.swing.JTable jTTablereportesanio;
    public javax.swing.JTable jTTablereportesmes;
    public com.toedter.calendar.JYearChooser jYManio;
    public com.toedter.calendar.JYearChooser jYanio;
    // End of variables declaration//GEN-END:variables
}
