/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import CONTROLADORES.EstadoClienteControlador;
import MODELOS.EstadoClienteBo;
import MODELOS.EstadoClienteVo;
import java.awt.Color;

/**
 *
 * @author mario
 */
public class VistaCliente extends javax.swing.JFrame {

    /**
     * Creates new form VistaCliente
     */
    public VistaCliente() {
        initComponents();
        jPconsul.setVisible(true);
        jPregis.setVisible(false);
        jPmod.setVisible(false);
        //LLenamos los comboBox
        EstadoClienteBo modelo = new EstadoClienteBo();
        EstadoClienteControlador estado = new EstadoClienteControlador(this,modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBr = new javax.swing.JButton();
        jBconsul = new javax.swing.JButton();
        jBmod = new javax.swing.JButton();
        jPregis = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTapellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTcel = new javax.swing.JFormattedTextField();
        jBregis = new javax.swing.JButton();
        jLverifiNom = new javax.swing.JLabel();
        jLverifiCel = new javax.swing.JLabel();
        jLverifiAp = new javax.swing.JLabel();
        jPmod = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTbuscar = new javax.swing.JTextField();
        jBbuscarId = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTnombreMod = new javax.swing.JTextField();
        jTapellidoMod = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTcelMod = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jBmodifi = new javax.swing.JButton();
        jLverifiNomMod = new javax.swing.JLabel();
        jLverifiApMod = new javax.swing.JLabel();
        jCestadoMod = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jPconsul = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTbusval = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTableclientes = new javax.swing.JTable();
        jBelim = new javax.swing.JButton();
        jBtodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(840, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 42, 42));

        jButton4.setBackground(new java.awt.Color(42, 42, 42));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/volver.png"))); // NOI18N
        jButton4.setToolTipText("Volver");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/002-noria.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTES");

        jBr.setBackground(new java.awt.Color(42, 42, 42));
        jBr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBr.setForeground(new java.awt.Color(255, 255, 255));
        jBr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/012-cartera.png"))); // NOI18N
        jBr.setText("Registrar");
        jBr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBr.setBorderPainted(false);
        jBr.setFocusPainted(false);
        jBr.setFocusable(false);
        jBr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrActionPerformed(evt);
            }
        });

        jBconsul.setBackground(new java.awt.Color(255, 255, 255));
        jBconsul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBconsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/005-busqueda.png"))); // NOI18N
        jBconsul.setText("Consultar");
        jBconsul.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBconsul.setBorderPainted(false);
        jBconsul.setFocusPainted(false);
        jBconsul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBconsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsulActionPerformed(evt);
            }
        });

        jBmod.setBackground(new java.awt.Color(42, 42, 42));
        jBmod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBmod.setForeground(new java.awt.Color(255, 255, 255));
        jBmod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/008-cuaderno.png"))); // NOI18N
        jBmod.setText("Modificar ");
        jBmod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jBmod.setBorderPainted(false);
        jBmod.setFocusPainted(false);
        jBmod.setFocusable(false);
        jBmod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBmod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBconsul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addGap(41, 41, 41)
                .addComponent(jBconsul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBmod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 450));

        jPregis.setBackground(new java.awt.Color(255, 255, 255));
        jPregis.setPreferredSize(new java.awt.Dimension(590, 450));
        jPregis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/012-cartera.png"))); // NOI18N
        jPregis.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setText("Registrar cliente");
        jPregis.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel8.setText(" * Nombre:");
        jPregis.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });
        jPregis.add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 182, 24));

        jLabel9.setText("  Apellido:");
        jPregis.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jTapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTapellidoActionPerformed(evt);
            }
        });
        jPregis.add(jTapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 182, 24));

        jLabel10.setText("*Celular:");
        jPregis.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jTcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcelActionPerformed(evt);
            }
        });
        jTcel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcelKeyTyped(evt);
            }
        });
        jPregis.add(jTcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 182, 24));

        jBregis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBregis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/006-libro.png"))); // NOI18N
        jBregis.setText("Registrar");
        jBregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregisActionPerformed(evt);
            }
        });
        jPregis.add(jBregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jLverifiNom.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLverifiNom.setForeground(new java.awt.Color(255, 0, 0));
        jPregis.add(jLverifiNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 190, 20));

        jLverifiCel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLverifiCel.setForeground(new java.awt.Color(255, 0, 0));
        jPregis.add(jLverifiCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 190, 20));

        jLverifiAp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLverifiAp.setForeground(new java.awt.Color(255, 0, 0));
        jPregis.add(jLverifiAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 190, 20));

        getContentPane().add(jPregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 0, 590, 450));

        jPmod.setBackground(new java.awt.Color(255, 255, 255));
        jPmod.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/008-cuaderno.png"))); // NOI18N
        jPmod.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 25, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel19.setText("Modificar cliente");
        jPmod.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 95, -1, -1));

        jLabel20.setText("Id");
        jPmod.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 145, -1, -1));

        jTbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTbuscar.setDragEnabled(true);
        jTbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbuscarActionPerformed(evt);
            }
        });
        jTbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTbuscarKeyTyped(evt);
            }
        });
        jPmod.add(jTbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 142, 180, -1));

        jBbuscarId.setText("Buscar");
        jPmod.add(jBbuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 175, -1, -1));

        jLabel21.setText(" Nombre:");
        jPmod.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 219, -1, -1));

        jTnombreMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreModActionPerformed(evt);
            }
        });
        jPmod.add(jTnombreMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 216, 182, -1));

        jTapellidoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTapellidoModActionPerformed(evt);
            }
        });
        jPmod.add(jTapellidoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 264, 182, -1));

        jLabel22.setText(" Apellido:");
        jPmod.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 267, -1, -1));

        jTcelMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcelModKeyTyped(evt);
            }
        });
        jPmod.add(jTcelMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 313, 182, -1));

        jLabel23.setText("Celular:");
        jPmod.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 316, -1, -1));

        jBmodifi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBmodifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/005-editar.png"))); // NOI18N
        jBmodifi.setText("Modificar");
        jBmodifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodifiActionPerformed(evt);
            }
        });
        jPmod.add(jBmodifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jLverifiNomMod.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLverifiNomMod.setForeground(new java.awt.Color(255, 0, 0));
        jPmod.add(jLverifiNomMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 190, 30));

        jLverifiApMod.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLverifiApMod.setForeground(new java.awt.Color(255, 0, 0));
        jPmod.add(jLverifiApMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 190, 30));

        jCestadoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCestadoModActionPerformed(evt);
            }
        });
        jPmod.add(jCestadoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 150, -1));

        jLabel25.setText("Estado:");
        jPmod.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        getContentPane().add(jPmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 0, 590, 450));

        jPconsul.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/005-busqueda.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setText("Consultar");

        jLabel5.setText("Ingrese palabra o número:");

        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/004-busqueda.png"))); // NOI18N
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jTTableclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTTableclientes);

        jBelim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/002-borrar.png"))); // NOI18N
        jBelim.setText("Eliminar");
        jBelim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBelimActionPerformed(evt);
            }
        });

        jBtodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32/003-bucle.png"))); // NOI18N
        jBtodos.setText("Cargar");

        javax.swing.GroupLayout jPconsulLayout = new javax.swing.GroupLayout(jPconsul);
        jPconsul.setLayout(jPconsulLayout);
        jPconsulLayout.setHorizontalGroup(
            jPconsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPconsulLayout.createSequentialGroup()
                .addGroup(jPconsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPconsulLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPconsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPconsulLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jBelim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtodos))))
                    .addGroup(jPconsulLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTbusval, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPconsulLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPconsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPconsulLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addGap(237, 237, 237))
        );
        jPconsulLayout.setVerticalGroup(
            jPconsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPconsulLayout.createSequentialGroup()
                .addGroup(jPconsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPconsulLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addGroup(jPconsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTbusval, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPconsulLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jBbuscar)))
                .addGap(18, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPconsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBelim)
                    .addComponent(jBtodos))
                .addContainerGap())
        );

        getContentPane().add(jPconsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 0, 590, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrActionPerformed
    
        jPregis.setVisible(true);
        jPconsul.setVisible(false);
        jPmod.setVisible(false);
        if(!jBr.isSelected()){
            jBr.setBackground(new Color(255, 255, 255));
            jBr.setForeground(new Color(42, 42, 42));
            jBconsul.setBackground(new Color(42, 42, 42));
            jBconsul.setForeground(new Color(255, 255, 255));
            jBmod.setBackground(new Color(42, 42, 42));
            jBmod.setForeground(new java.awt.Color(255, 255, 255));

        }
    }//GEN-LAST:event_jBrActionPerformed

    private void jBconsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsulActionPerformed
        
        jPconsul.setVisible(true);
        jPregis.setVisible(false);
        jPmod.setVisible(false);
        
        if(!jBconsul.isSelected()){
            jBr.setBackground(new Color(42, 42, 42));
            jBr.setForeground(new java.awt.Color(255, 255, 255));
            jBconsul.setBackground(new Color(255, 255, 255));
            jBconsul.setForeground(new Color(42, 42, 42));
            jBmod.setBackground(new Color(42, 42, 42));
            jBmod.setForeground(new java.awt.Color(255, 255, 255));

        }
    }//GEN-LAST:event_jBconsulActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        VistaInicio vista = new VistaInicio();
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodActionPerformed
        
        jPmod.setVisible(true);
        jPconsul.setVisible(false);
        jPregis.setVisible(false);
        
        if(!jBmod.isSelected()){
            jBr.setBackground(new Color(42, 42, 42));
            jBr.setForeground(new java.awt.Color(255, 255, 255));
            jBconsul.setBackground(new Color(42, 42, 42));
            jBconsul.setForeground(new java.awt.Color(255, 255, 255));
            jBmod.setBackground(new Color(255, 255, 255));
            jBmod.setForeground(new Color(42, 42, 42));
        }

    }//GEN-LAST:event_jBmodActionPerformed

    private void jBregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregisActionPerformed

    }//GEN-LAST:event_jBregisActionPerformed

    private void jTcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcelActionPerformed

    private void jTapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTapellidoActionPerformed

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreActionPerformed

    private void jTnombreModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreModActionPerformed

    private void jTapellidoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTapellidoModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTapellidoModActionPerformed

    private void jBmodifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodifiActionPerformed

    }//GEN-LAST:event_jBmodifiActionPerformed

    private void jTcelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcelKeyTyped
        char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTcelKeyTyped

    private void jTcelModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcelModKeyTyped
        char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTcelModKeyTyped

    private void jBelimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBelimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBelimActionPerformed

    private void jTbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbuscarActionPerformed

    private void jTbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscarKeyTyped
        char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTbuscarKeyTyped

    private void jCestadoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCestadoModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCestadoModActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBbuscar;
    public javax.swing.JButton jBbuscarId;
    private javax.swing.JButton jBconsul;
    public javax.swing.JButton jBelim;
    public javax.swing.JButton jBmod;
    public javax.swing.JButton jBmodifi;
    private javax.swing.JButton jBr;
    public javax.swing.JButton jBregis;
    public javax.swing.JButton jBtodos;
    private javax.swing.JButton jButton4;
    public javax.swing.JComboBox<EstadoClienteVo> jCestadoMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLverifiAp;
    public javax.swing.JLabel jLverifiApMod;
    public javax.swing.JLabel jLverifiCel;
    public javax.swing.JLabel jLverifiNom;
    public javax.swing.JLabel jLverifiNomMod;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPconsul;
    private javax.swing.JPanel jPmod;
    private javax.swing.JPanel jPregis;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    public javax.swing.JTable jTTableclientes;
    public javax.swing.JTextField jTapellido;
    public javax.swing.JTextField jTapellidoMod;
    public javax.swing.JTextField jTbuscar;
    public javax.swing.JTextField jTbusval;
    public javax.swing.JFormattedTextField jTcel;
    public javax.swing.JFormattedTextField jTcelMod;
    public javax.swing.JTextField jTnombre;
    public javax.swing.JTextField jTnombreMod;
    // End of variables declaration//GEN-END:variables
}
